linters:

  ImportPath:
    leading_underscore: true

  LeadingZero:
    style: 'include_zero'

  VendorPrefix:
    exclude:
      - '_sass/_mixins.scss'

  SelectorFormat:
    convention: 'hyphenated_BEM'

  NestingDepth:
    max_depth: 4
